### ISSUE TITLE
zk Sync Test wallet : error when funding

### ISSUE THREAD

**Issue by spolrot** [matter-labs/zksync#223]
Hi guys. Just trying the ZK Sync Test Wallet.

I have an error message in the UI when I try to fund my wallet ("Found 0 PQ IDs") 
+
the transaction fails. 
e.g. tx number 0x633a23c8ec9dab6ff52e68f4b35c907a8486b33c65fd80df833b71a086647c3f
https://rinkeby.etherscan.io/tx/0x633a23c8ec9dab6ff52e68f4b35c907a8486b33c65fd80df833b71a086647c3f

Fails with error message "fdh11"

**Comment by gluk64** [comment]
This behavior is fine. I suggest to simply increase the required `value` to 10x of the nominal value, so that the user may increase the gas price up to 10x.

The user shall be prepared that the price of deposit or other priority operations will be proportional to the price she pays to miners for this transaction, period.
