### ISSUE TITLE
TokenInit and KeysWithPlonkVerifier Contracts missing in repo

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [matter-labs/zksync#233]
There are _seemingly_ 2 contracts missing in the repo

- DeployFactory.sol imports TokenInit.sol but the TokenInit contract is not in the repo folder: https://github.com/matter-labs/zksync/tree/breaking/contracts/contracts
- Verifier.sol imports and is KeysWithPlonkVerifier contract but the KeysWithPlonkVerifier contract is not in the repo folder

I might be blind but I could not find them.

I am currently creating a smart contract system architecture diagram to understand the contract relationships and functions and then abstract out the required structure and functions to adapt it to the Baseline protocol (https://github.com/ethereum-oasis/baseline/tree/master) to make the protocol a) scalable and b) extensible by leveraging the PLONK framework.

**Comment by dvush** [comment]
Hi, this contracts are not in the repo `contracts` directory since they are generated before compiling.

* `TokenInit` is generated from the list of the initial tokens `etc/tokens`, here is code and template: https://github.com/matter-labs/zksync/tree/breaking/core/models/src/bin/gen_token_add_contract
* `KeysWithPlonkVerifier.sol` contains verification keys for our zkp circuit with various block sizes, here is code and template: https://github.com/matter-labs/zksync/tree/breaking/core/key_generator/src/verifier_contract_generator

**Comment by gluk64** [comment]
Hi @Therecanbeonlyone1969, we will be happy to help you with using PLONK and zkSync tech in Baseline, how about a quick call to discuss? Added you in LinkedIn.

**Comment by Therecanbeonlyone1969** [comment]
@dvush -- thank you so much for the clarification! Got it now! @gluk64 I saw your invitation and message and replied. Happy to hop on a call at any time.
